sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: HHgGBJ3dVu4ZfJMT3EEFRyczcKyu/WAL8AhAxYd9fOA57TQY9zBImaAYrfW+6z9ewRaCUShx3H/qWkJBxSCNaKSppJ8XAKPxET3TpfjiwHdoce93Ji3hWuOz4rKJrEPB87sS9UNvIWgFiO+Q6yCD22VVLok1akhWhSNAATBDbNGgxemAmLPMIf34G5+xXXQ/UKiLJXfKQP7cMpEIGzZoGGi1SY0ktLwgd57eY9bk65Yuyzdz9+kpB46D/gdyw6JwljuSsxT8DGODkF+ln7YdCkDqpcd8EW2Rg+REhVlpZpmsSVQWmp+uuW+fMGO29mwNF1UjPZKznmWkMVoXUEr7I7DQ4CCs0l50q/Etb+fUGoNOQL8nxo6EPDY5kbbmjb2un3Hc7PtBlA69RlAV47Ow4UFRv6/BahSXbbw9UIof7arILw6nSNeSFLoWRKXneaOcIg6Qx+isUN+b59cGSpg5tvU9wT6DiGCNNv1+iYnVoVypy0V4qq5i9C4zjtP7znQvt/W9cYxbF/P2k/yk6jWzXVzd+mA9zZU4zrnegzipDCEgKW2T/Jt8+QXjxePF5RYU8RI3F/8y3lC3GMMwfArLg0+HRAFR5dc3+UNx1ZySChQiAcxoveMzzTOt8h5nhVHWvDspXuCy6b2dOljDgzhWtySh5cNYKIxkJhAau2nnfBU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Sketches-New-and-Old-Part-1._5836
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy